name: 'docker-sign'
description: 'Sign docker images'
inputs:
  image-ref:
    description: 'The Docker image ref, example: imagename:tag'
    required: true
  private-key-id:
    description: 'The Docker private key id (hash)'
    required: true
  private-key:
    description: 'The Docker private key'
    required: true
  private-key-passphrase:
    description: 'The Docker private key passphrase'
    required: true
  private-key-name:
    description: 'The Docker private key name'
    required: false
  sign-manifest:
    description: 'Use docker notary and manifests'
    required: false
    default: false
  notary-server:
    description: 'The URL to the notary server'
    required: false
    default: 'https://notary.docker.io'
  notary-auth:
    description: 'The credentials in auth basic format'
    required: false


branding:
    icon: "feather"
    color: gray-dark

runs:
  using: "composite"
  steps:
    - run: mkdir -p ~/.docker/trust/private/
      shell: sh
    - run: echo "${{ inputs.private-key }}" > ~/.docker/trust/private/${{ inputs.private-key-id }}.key
      shell: sh
    - run: chmod 600 ~/.docker/trust/private/${{ inputs.private-key-id }}.key
      shell: sh
    - run: docker trust key load ~/.docker/trust/private/${{ inputs.private-key-id }}.key
      shell: sh
      env:
        DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: "${{ inputs.private-key-passphrase }}"
        DOCKER_CONTENT_TRUST: 1
    - run: |
        if [ "${{ inputs.sign-manifest}}" != "true" ]; then
            docker trust sign "${{ inputs.image-ref }}";
        fi
      shell: sh
      env:
        DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: "${{ inputs.private-key-passphrase }}"
        DOCKER_CONTENT_TRUST: 1
    - run: |
        if [ "${SIGN_MANIFEST_MODE}" = "true" ]; then
            echo "${{ inputs.private-key }}" > ~/.docker/trust/private/${{ inputs.private-key-id }}.key
            notary --debug key import ~/.docker/trust/private/${{ inputs.private-key-id }}.key -r "${{ inputs.private-key-name }}" -d ~/.docker/trust
            notary key list -d ~/.docker/trust/
            SHA_256="$(docker manifest push "${IMAGE_REF}" | cut -d ':' -f 2)";
            REF="$(echo "${IMAGE_REF}" | cut -d ':' -f 1)";
            TAG="$(echo "${IMAGE_REF}" | cut -d ':' -f 2)";
            echo "Manifest SHA-256: ${SHA_256}";
            export NOTARY_AUTH="$(printf "${AUTH_BASIC}" | base64 -w0)";
            unset AUTH_BASIC;
            notary addhash -p -s "${{ inputs.notary-server }}" "${REF}" "${TAG}" 946 --sha256 "${SHA_256}" -r "targets/${{ inputs.private-key-name }}" --verbose --debug;
            notary list "${REF}" -s "${{ inputs.notary-server }}";
            unset NOTARY_AUTH;
        else
            docker trust sign "${IMAGE_REF}";
        fi
      shell: sh
      env:
        AUTH_BASIC: "${{ inputs.notary-auth }}"
        IMAGE_REF: "${{ inputs.image-ref }}"
        SIGN_MANIFEST_MODE: "${{ inputs.sign-manifest }}"
        DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: "${{ inputs.private-key-passphrase }}"
        NOTARY_DELEGATION_PASSPHRASE: "${{ inputs.private-key-passphrase }}"
        DOCKER_CONTENT_TRUST: 1
        DOCKER_CLI_EXPERIMENTAL: enabled
    - run: docker trust inspect --pretty "${{ inputs.image-ref }}"
      shell: sh
      env:
        DOCKER_CONTENT_TRUST: 1
    - run: rm ~/.docker/trust/private/${{ inputs.private-key-id }}.key
      shell: sh
    - run: rm -rf ~/.docker/trust/private
      shell: sh
