name: 'docker-sign'
description: 'Sign docker images'
inputs:
  image-ref:
    description: 'The Docker image ref, example: imagename:tag'
    required: true
  private-key-id:
    description: 'The Docker private key id (hash)'
    required: true
  private-key:
    description: 'The Docker private key'
    required: true
  private-key-passphrase:
    description: 'The Docker private key passphrase'
    required: true
  private-key-name:
    description: 'The Docker private key name'
    required: false
  sign-manifest:
    description: 'Use docker notary and manifests'
    required: false
    default: false
  notary-server:
    description: 'The URL to the notary server'
    required: false
    default: 'https://notary.docker.io'

branding:
    icon: "feather"
    color: gray-dark

runs:
  using: "composite"
  steps:
    - run: mkdir -p ~/.docker/trust/private/
      shell: sh
    - run: echo "${{ inputs.private-key }}" > ~/.docker/trust/private/${{ inputs.private-key-id }}.key
      shell: sh
    - run: chmod 600 ~/.docker/trust/private/${{ inputs.private-key-id }}.key
      shell: sh
    - run: docker trust key load ~/.docker/trust/private/${{ inputs.private-key-id }}.key
      shell: sh
      env:
        DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: "${{ inputs.private-key-passphrase }}"
        DOCKER_CONTENT_TRUST: 1
    - run: |
        if [ "${{ inputs.sign-manifest}}" != "true" ]; then
            docker trust sign "${{ inputs.image-ref }}";
        fi
      shell: sh
      env:
        DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: "${{ inputs.private-key-passphrase }}"
        DOCKER_CONTENT_TRUST: 1
    - run: |
        if [ "${{ inputs.sign-manifest}}" = "true" ]; then
            SHA_256="$(DOCKER_CLI_EXPERIMENTAL=enabled docker manifest push "${{ inputs.image-ref }}" | cut -d ':' -f 2)";
            REF="$(echo "${{ inputs.image-ref }}" | cut -d ':' -f 1)";
            TAG="$(echo "${{ inputs.image-ref }}" | cut -d ':' -f 2)";
            echo "Manifest SHA-256: ${SHA_256}";
            export NOTARY_AUTH="$(printf "${{ secrets.DOCKER_REPOSITORY_LOGIN }}:${{ secrets.DOCKER_REPOSITORY_PASSWORD }}" | base64 -w0)";
            notary addhash -s "${{ inputs.notary-server }}" -p "${REF}" "${TAG}" 946 --sha256 "${SHA_256}" -r "targets/${{ inputs.private-key-name }}";
            notary list "${REF}" -s "${{ inputs.notary-server }}";
            unset NOTARY_AUTH;
        else
            docker trust sign "${{ inputs.image-ref }}";
        fi
      shell: sh
      env:
        DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: "${{ inputs.private-key-passphrase }}"
        DOCKER_CONTENT_TRUST: 1
    - run: docker trust inspect --pretty "${{ inputs.image-ref }}"
      shell: sh
      env:
        DOCKER_CONTENT_TRUST: 1
    - run: rm ~/.docker/trust/private/${{ inputs.private-key-id }}.key
      shell: sh
    - run: rm -rf ~/.docker/trust/private
      shell: sh
